### ISSUE TITLE
get_context() takes 2 positional arguments but 4 were given error

### ISSUE THREAD

**Issue by miiga** [AccentDesign/wagtailstreamforms#116]
Sorry rookie mistake

**Comment by stuartaccent** [comment]
cool ty @miiga

**Comment by aidan2129** [comment]
@miiga how did you resolve this? having the same issue but got that error on a previous site i used this on.

**Comment by aidan2129** [comment]
Never mind think i have worked it out now lol

**Comment by biglong122** [comment]
@miiga hello. I have same problem, but how do you solve this issue?
