### ISSUE TITLE
Cannot find public url of streamform

### ISSUE THREAD

**Issue by Chingiz** [AccentDesign/wagtailstreamforms#118]
Where can I get public url of created form?

**Comment by stuartaccent** [comment]
Hi @Chingiz 

The created forms can be added to a page via a streamfield or a template tag, see https://wagtailstreamforms.readthedocs.io/en/latest/usage.html. As long as you are adding them to a page served via wagtail everything else will fall into place. The url will just be the public facing url of the page in wagtail.

Does this help?

Ty, Stu

**Comment by Chingiz** [comment]
Thank you!
