### ISSUE TITLE
Ability to duplicate a form

### ISSUE THREAD

**Issue by timaccent** [AccentDesign/wagtailstreamforms#12]
The ability to duplicate a form, including all data for form fields.

**Comment by stuartaccent** [comment]
@timaccent ive had a little play around with this last night, is it ok if there was a button on the form list 'copy' then it duplicates and reloads the list. can make the name something like 

#COPY : Some Form

then it will be at the top of the list when the list loads

Stu

**Comment by timaccent** [comment]
That sounds good, something like below maybe?
![forms-duplicate-button](https://user-images.githubusercontent.com/20127385/31820075-6dbfc540-b597-11e7-90e5-03e9efa5c20e.png)
Would a user want to go straight into the form? Possably not I guess, as they may want to duplicate more than 1 form before going in and editing.

**Comment by stuartaccent** [comment]
was thinking go to a screen that lets u change the name then save > go to list

![screen shot 2017-10-20 at 13 22 44](https://user-images.githubusercontent.com/20105514/31820582-d0f876be-b599-11e7-99ad-032dfdfa25a7.png)

same as what duplicating pages is

**Comment by stuartaccent** [comment]
so one at a time :)

**Comment by timaccent** [comment]
That all sounds good.
