### ISSUE TITLE
Update to wagtail 2.5

### ISSUE THREAD

**Issue by krishnan-vignesh** [AccentDesign/wagtailstreamforms#121]
Hi, we are using wagtailstreamforms in our project and we really like it. Recently, we encountered an issue where we were not able to set links as "nofollow" rel. [https://github.com/wagtail/wagtail/issues/4474#issuecomment-474430048](url) This answer solved our issue but for this to run we needed wagtail 2.5 and wagtailstreamforms doesn't support 2.5 yet. So, I would like to know when you are planning to support wagtail 2.5?

Thanks

**Comment by stuartaccent** [comment]
Hi @krishnan-vignesh, yes we are in short, I will look to update by the end of today. Will msg you when its published :)

Cheers, Stu

**Comment by krishnan-vignesh** [comment]
Thank you very much @stuartaccent.

**Comment by krishnan-vignesh** [comment]
Hi, I was wondering if you have been able to do this. This is kind of urgent for us. If you can also guide us what may need fixing I will try myself if possible for me to do.

**Comment by stuartaccent** [comment]
Hi @krishnan-vignesh 

Sorry for the delay, it's done. Any issues please shout

Stu
