### ISSUE TITLE
How to get 'required' field data in the template?

### ISSUE THREAD

**Issue by vinodMS** [AccentDesign/wagtailstreamforms#125]
### Expected behaviour
{{ field.required }} in the form_fields.html template should output True/False based on the form input.

### Actual behaviour
{{ field.required }} is not outputting any data

### Steps to reproduce the behaviour
Create a new template(form_block.html) and override the form_fields.html file to include {{ field.required }} in the template.

**Comment by stuartaccent** [comment]
Hi @vinodMS 

I’m not able to try at the moment but I think it’s {{ field.field.required }}. Let me know if it works. 

Stu

**Comment by vinodMS** [comment]
Perfect, that did the trick. Thanks a lot and great work.

**Comment by stuartaccent** [comment]
NP @vinodMS ty
