### ISSUE TITLE
Not compatible with latest Wagtail release v 2.7

### ISSUE THREAD

**Issue by dantabel** [AccentDesign/wagtailstreamforms#133]
### Expected behaviour
Expect to be able to install on latest wagtail 

### Actual behaviour
Installing wagtailstreamforms downgrades wagtail to v 2.6.3

### Steps to reproduce the behaviour
`pip install wagtailstreamforms`

**Comment by stuartaccent** [comment]
hi @dantabel 

this is currently being tested at our end and will look to publish it tomorrow

cheers

**Comment by dantabel** [comment]
Great news! Thanks 🥇

**Comment by stuartaccent** [comment]
Hi @dantabel 
Should be all done v3.8.0 released :)
