### ISSUE TITLE
CSRF verification fails when submiting form

### ISSUE THREAD

**Issue by sect2k** [AccentDesign/wagtailstreamforms#51]
This happens because `{% csrf_token %}` tag  in `form_block.html` template can not render without request in context.

wagtail: 1.13.1

**Comment by stuartaccent** [comment]
hi @sect2k, would you please be able to provide more info on how and from where the `WagtailFormBlock` is rendered from as im not able to reproduce this locally. Just trying to isolate the reason as to why the request is not in the context for you specifically. 

Cheers

**Comment by stuartaccent** [comment]
The only thin i can think of is that your streamfield is being iterated over by the means of 
```
{% for block in page.body %}
    {{ block }}
{% endfor %}
```
when it should be
```
{% load wagtailcore_tags %}
{% for block in page.body %}
    {% include_block block %}
{% endfor %}
```
please see http://docs.wagtail.io/en/v1.9/topics/streamfield.html#template-rendering 8 code blocks down where it starts with `Writing {{ my_block }} is roughly equivalent to {% include_block my_block %}, but the short form is more restrictive, as it does not pass variables from the calling template such as request or page`.

Please advise if this is your situation, Ty

**Comment by sect2k** [comment]
@stuartaccent, that was indeed it, thank you, you're the best. Looks like `{% include_block  %} made it to wagtail, since I used it last.

Thanks for the great package, love it.

**Comment by stuartaccent** [comment]
Hi @sect2k, no problem, getting that added to our docs. If theres any feature you would like to see added then give us a shout and we can look into it :)
