### ISSUE TITLE
Wagtail 2.0 upgrading

### ISSUE THREAD

**Issue by SalahAdDin** [AccentDesign/wagtailstreamforms#60]
I was reviewing this package and i saw some code lines that could be a problem with the next `wagtail` release version: some imports for example.

Have you thought update this package for the next version?

**Comment by SalahAdDin** [comment]
I'm getting the next problem with `wagtail 2.0`, after upgrade this package a lot of course:
```
TemplateDoesNotExist at /admin/wagtailstreamforms/basicform/
modeladmin/wagtailstreamforms/basicform/index.html, modeladmin/wagtailstreamforms/index.html, modeladmin/index.html
```
![noexiste](https://user-images.githubusercontent.com/5034215/35485087-376e75ea-046b-11e8-9df0-ac0e2071c325.png)

**Comment by SalahAdDin** [comment]
It's related: https://github.com/AccentDesign/wagtailstreamforms/pull/61

**Comment by stuartaccent** [comment]
Hi @SalahAdDin,

Thanks for this, I am already on the case. We have a v2 branch on the go with everything updated.

https://github.com/AccentDesign/wagtailstreamforms/tree/v2

We are currently deciding if it should support wagtail 1x but think it will just make life awkward :)

What are your thoughts on this?

Cheers Stu

**Comment by SalahAdDin** [comment]
@stuartaccent I think the same, in all package that i saw they put in documentation a compatibility table: Until current or a minor next release you can support `wagtail 1.x`, after the next major release you only will support `wagtail > 2.x`, it will make more easy support the next release version.

**Comment by stuartaccent** [comment]
@SalahAdDin cheers, thats settled then :)

**Comment by stuartaccent** [comment]
completed, 2.0 released
