### ISSUE TITLE
Missed template files 

### ISSUE THREAD

**Issue by SalahAdDin** [AccentDesign/wagtailstreamforms#62]
I'm new using this package, i get this bug:
```
TemplateDoesNotExist at /admin/wagtailstreamforms/basicform/
modeladmin/wagtailstreamforms/basicform/index.html, modeladmin/wagtailstreamforms/index.html, modeladmin/index.html
```
![noexiste](https://user-images.githubusercontent.com/5034215/35485087-376e75ea-046b-11e8-9df0-ac0e2071c325.png)

I though it was a `wagtail 2.0` related problem, but not, i'm testing it now with `1.13.x` version and i am still getting this problem.

What's happening?

**Comment by stuartaccent** [comment]
hi @SalahAdDin 

do you have the modeladmin app in your installed apps?

INSTALLED_APPS = [
    ...
    'wagtail.contrib.modeladmin',
    'wagtail.wagtailforms',
    'wagtailstreamforms'
    ...
]

Cheers

**Comment by SalahAdDin** [comment]
@stuartaccent You are right, i'm sorry.
