### ISSUE TITLE
Issue with package migrations

### ISSUE THREAD

**Issue by catherine-mcdonough** [AccentDesign/wagtailstreamforms#70]
I have an issue with the package migrations changes. 

After a fresh install of wagtailstreamforms I get this.. 

```
Migrations for 'wagtailstreamforms':
  env/lib/python3.6/site-packages/wagtailstreamforms/migrations/0012_auto_20180315_1532.py
    - Alter field field_type on formfield
```

Steps to recreate.. 
1) `pip install wagtailstreamforms`
2) enable in base.py
3) `python manage.py makemigrations --check`

The functionality seems to be fine, however it does bring up some errors when I run tests against my site.

**Comment by stuartaccent** [comment]
Hi @catherine-mcdonough,

Hope you are well, apologies about this was a migration issue. Please could you try with:

```
pip install git+https://github.com/AccentDesign/wagtailstreamforms.git@missing_migrations
```

If the above works will get it merged and deployed.
Btw, Just wanted to check you were using wagtail 2? 

Cheers, Stu

**Comment by catherine-mcdonough** [comment]
Hi @stuartaccent 

That's great, thank you. I'll give it a go now!

Yeah, I'm using wagtail 2 

Thanks, 
Catherine

**Comment by catherine-mcdonough** [comment]
Just tested the updated version and it seems to be working 👍 

Thanks! 

Catherine

**Comment by stuartaccent** [comment]
Thanks, @catherine-mcdonough, Lubbly Jubbly.

Will be live in a few mins.

Stu

**Comment by stuartaccent** [comment]
@catherine-mcdonough v 2.0.1 on pypi :)
