### ISSUE TITLE
Wagtail forms separation or decommission

### ISSUE THREAD

**Issue by stuartaccent** [AccentDesign/wagtailstreamforms#73]
Due to the work in wagtail first hatch and the redevelopment of forms, look into and gather requirements into separating the project from the internal forms module.

Is this project still needed?
Does it bring enough once their work is complete.
How to handle form fields?
Adding additional fields?
Admin layout could be improved
Form field widget attrs
Anything else

What we dont want is to keep it as is, if we decide to continue with it, it will need form field code pulled out as wagtail is where the form fields are defined. We want to keep it consistent ie if they are adding fields via a stream field it seems odd to do it here a different way.

**Comment by BertrandBordage** [comment]
Yes, the idea is to move upstream a `StreamField` form builder that would be extendable enough that almost all use cases would be possible with a minimum of work. So ideally, this project should no longer be needed.

However, if I were you I would keep doing some support on this project until my work is done, especially that you now made it Wagtail 2 compatible :) It’s only a few months of extra support! Then you can decide whether it’s a good idea or not to drop it.

In the meantime, please specify in wagtail/wagtail#4485 in which way you would like to improve the form builder that isn’t already in my plan :) It’ll help me designing a future-proof developer interface, and maybe add some features if they are must have!

**Comment by stuartaccent** [comment]
Hi @BertrandBordage,

Thanks for the above, we did have some rough ideas of where we were going to take this project in the following months but nothing concrete thats worth sharing at this stage. 

What I imagine will happen is like you say support until your work is done and we will stop publishing this and just continue to do what we ever we plan offline, be it in a separate repo/branch etc. If there is anything that comes out of it we feel may be useful to the wider community we will come back with feature requests or what ever.

Stu
